spring:
  application:
    name: api-gateway

server:
    port: ${SERVER_PORT_API_GATEWAY}

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health